[package]
name = "chatgbt-buddy"
version = "1.0.0"
edition = "2021"
description = "Talk to Chatgbt on the CLI"

[dependencies]
serde_json = "*"
json = "*"
serde = { version = "*", features = ["derive"] }
reqwest = { version = "*", features = ["json", "stream", "multipart"] }
tokio = { version = "*", features = ["full"] }
log = "*"
structopt = "0.3.26"
clap = { version = "2.34.0"}
env_logger = "*"
whoami = "*"
atty = "*"
tokio-util = { version = "*", features = ["codec"] }
